version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: data-portal
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    networks:
      - nestjs-network

  realtor:
    image: realtor:latest
    depends_on:
      - dev-database
    container_name: realtor
    env_file: .env
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PRODUCT_KEY_SECRET=${PRODUCT_KEY_SECRET}
      - JSON_TOKEN_KEY=${JSON_TOKEN_KEY}
    networks:
      - nestjs-network

networks:
  nestjs-network:
